version: '3'
networks:
  saltstack:
services:
  salt-master:
    image: salt-master:latest
    container_name: salt-master
    ports:
      - "8000:8000"
      - "4505:4505"
      - "4506:4506"
    networks:
      - saltstack
  salt-minion:
    image: salt-minion:latest
    container_name: salt-minion
    networks:
      - saltstack
    depends_on:
        - salt-master
